[server]
headless = true
enableCORS = false
port = 8501
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#4CAF50"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"
